Document: winmod
Title: Debian winmod Manual
Author: <insert document author here>
Abstract: This manual describes what winmod is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/winmod/winmod.sgml.gz

Format: postscript
Files: /usr/share/doc/winmod/winmod.ps.gz

Format: text
Files: /usr/share/doc/winmod/winmod.text.gz

Format: HTML
Index: /usr/share/doc/winmod/html/index.html
Files: /usr/share/doc/winmod/html/*.html
